#!/bin/bash

DIR=$(dirname "$0")

# https://github.com/brndnmtthws/conky/issues/20
export LANG=en_US.UTF-8
# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1, "click_events": true}'
# Begin the endless array.
echo '['
# We send an empty first array of blocks to make the loop simpler:
echo '[],'
# Now send blocks with information forever:
conky -c "$DIR/conky.conf" &
conky_pid=$!

# Input loop - click event handler.
while read ; do
    # Input data may start with `,` - need to remove it to get valid JSON.
    echo "$REPLY" | sed -re 's/^,//' | "$DIR/status-event-handler"
done

echo 'i3: status: input loop has stopped' >&2
wait $conky_pid
