#!/usr/bin/env zsh

umask g-w,o-w
cd "$HOME"

echo '>>> Update Git submodules'
yadm submodule sync --recursive  # needed to sync URLs from .gitmodules
yadm submodule update --recursive --init

echo '>>> Change Git push URL'
yadm remote set-url --push origin 'git@gitlab.com:fpob/dotfiles.git'

echo '>>> Init Vim'
make -C .config/vim init

echo '>>> Configure mate/i3 desktop'
.config/i3/mate-setup.sh || echo "Retry with running X-session-manager"

echo '>>> Enable systemd user units'
systemctl --user enable --now \
    dunst.service cron@daily.timer

echo '>>> Create XDG data directories'
# Some apps fall back to `~/.<app>` if XDG dirs does not exist.
mkdir -p .local/share/tig
mkdir -p .local/state/less
mkdir -p .local/state/pspg
