" Settings -----------------------------------------------------------------{{{1

set nocompatible

" XDG directories
set runtimepath^=~/.config/vim,~/.local/share/vim
set runtimepath+=~/.config/vim/after,~/.local/share/vim/after
set packpath^=~/.config/vim,~/.local/share/vim
set packpath+=~/.config/vim/after,~/.local/share/vim/after
set viminfo+=n~/.local/share/vim/viminfo
set backupdir=~/.local/share/vim/backup// | call mkdir(&backupdir, 'p', 0700)
set directory=~/.local/share/vim/swap// | call mkdir(&directory, 'p', 0700)
set undodir=~/.local/share/vim/undo// | call mkdir(&undodir, 'p', 0700)
set viewdir=~/.local/share/vim/view// | call mkdir(&viewdir, 'p', 0700)

set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set backup  " make backup before overwriting a file
set breakindent
set colorcolumn=+1,+9
set complete=.,w,b,u,t
set confirm  " don't fail, instead show a dialog
set copyindent
set cscopeverbose
set cursorline  " highlight cursor line
set display=lastline
set expandtab  " expand tab to spaces
set fileencoding=utf-8  " encoding for writing files
set foldmethod=marker
set formatoptions=tcqj
set history=1000
set hlsearch
set ignorecase
set incsearch
set langnoremap
set laststatus=2
set lazyredraw
set linebreak  " don't wrap words in the middle, see 'breakat'
set listchars=tab:›\ ,nbsp:~
set list  " display some whitespace chars, see 'listchars'
set nojoinspaces
set nolangremap
set nostartofline
set nrformats=bin,hex
set number
set preserveindent
set ruler
set scrolloff=4
set shiftwidth=4
set showbreak=↳
set showcmd
set sidescrolloff=4
set smartcase
set smarttab
set splitbelow
set splitright
set switchbuf=uselast
set tabpagemax=50
set tabstop=4
set textwidth=80
set title  " set terminal title
set titlestring=vim:\ %f\ %r%m
set ttyfast
set virtualedit=block  " cursor can be positioned where there is no char
set wildchar=<Tab>
set wildmenu
set wildmode=full
set wildoptions=pum,tagfile
set wrap

if v:version >= 800
    set belloff=all  " no sound or visual bell
endif

if has('persistent_undo')
    set undofile  " persistent undo
endif

if has('conceal')
    set conceallevel=0
    set concealcursor=n
endif

if has('mouse')
    set mouse=a  " enable mouse
endif

if has('unnamedplus')
    set clipboard=unnamedplus  " use '+' register for all y/d/c operations
endif

if has('gui_running')
    set guioptions=acgit  " hide buttons, scroll, ...
    set guifont=Hack\ 9
endif

" Enable syntax
syntax enable
filetype plugin indent on

" Mappings -----------------------------------------------------------------{{{1

let mapleader = ","

" Keep selection when indenting/outdenting
vnoremap < <gv
vnoremap > >gv

" Yank to the end
nnoremap Y y$

" Tab switching
nnoremap <C-h> gT
nnoremap <C-l> gt

" Window switching (alt)
nnoremap <M-h> <C-w>h
nnoremap <M-l> <C-w>l
nnoremap <M-k> <C-w>k
nnoremap <M-j> <C-w>j

" Word to uppercase
inoremap <C-u> <esc>viwUea

" Faster saving and closing
nnoremap <F2> <Cmd>w<Cr>
nnoremap <F3> <Cmd>x<Cr>
nnoremap <F4> <Cmd>q<Cr>

" Un-highlight search, update diff and refresh screen
nnoremap <F5> <Cmd>nohlsearch<Bar>diffupdate<Cr>

" Autocommands -------------------------------------------------------------{{{1

augroup ftplugins
    autocmd!
    autocmd FileType go,make setlocal noexpandtab
    autocmd FileType yaml,toml setlocal tabstop=2 shiftwidth=2
augroup END
