#!/usr/bin/env bash

if [[ $1 == '--help' ]] ; then
    cat <<EOF
Použití: $(basename "$0") [-f FROM_ENCONDING] [INPUT [OUTPUT]]

Převede text na ASCII, ne-ASCII znaky nahrazuje ASCII ekvivalenty
(ě → e, ý → y, ...).
Bez paramertů převádí UTF-8 ze stdin na stdout.
EOF
    exit
fi

from=utf-8

while getopts f:o:i: opt ; do
    case $opt in
        f) from=$OPTARG ;;
        *) echo "Neznámý přepínač '$opt'" ;;
    esac
done
shift $((--OPTIND))

input=${1:--}
output=${2:--}

iconv -f "$from" -t ascii//TRANSLIT -o "$output" "$input"
