#!/usr/bin/env python3

import click
import cairo


def rgba(hex_rgba):
    return (int(hex_rgba[0:2], 16) / 255,
            int(hex_rgba[2:4], 16) / 255,
            int(hex_rgba[4:6], 16) / 255,
            int(hex_rgba[6:8], 16) / 255 if len(hex_rgba) == 8 else 1.0)


@click.command()
@click.argument('width', type=click.IntRange(min=100))
@click.argument('height', type=click.IntRange(min=100))
@click.argument('output', type=click.Path(exists=False))
@click.option('-c', '--color', default='ffffffff')
@click.option('-b', '--border', default='000000ff')
def cli(width, height, output, color, border):
    image = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
    ctx = cairo.Context(image)

    ctx.set_line_width(4)
    ctx.set_line_join(cairo.LINE_JOIN_MITER)
    ctx.rectangle(0, 0, width, height)

    ctx.set_source_rgba(*rgba(color))
    ctx.fill_preserve()

    ctx.set_source_rgba(*rgba(border))
    ctx.stroke()

    text = "{}x{}".format(width, height)
    ctx.set_font_size(min(min(width, height) / 8, 100))
    _, _, text_width, text_height, _, _ = ctx.text_extents(text)
    ctx.move_to(width / 2 - text_width / 2, height / 2 + text_height / 2)
    ctx.show_text(text)

    image.write_to_png(output)


if __name__ == '__main__':
    # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    cli()
