#!/usr/bin/env bash

set -o pipefail

git-fzf-branch () {
    git branch --all --format '%(refname:short)' \
        | fzf --exit-0
}

git-fzf-checkout () {
    local branch=$(git-fzf-branch)
    [[ -z $branch ]] && return 1
    git checkout "$branch"
}

git-fzf-merge () {
    local branch=$(git-fzf-branch)
    [[ -z $branch ]] && return 1
    git merge $branch
}

git-fzf-log () {
    git log --color=always --reverse --pretty=format:'%C(auto)%h%Creset  %s' \
        | fzf --ansi --tac \
        | cut -f1 -d' '
}

git-fzf-fixup () {
    local commit=$(git-fzf-log)
    [[ -z $commit ]] && return 1
    git commit --fixup "$commit"
}

git-fzf-cherry-pick () {
    local commit=$(git-fzf-log)
    [[ -z $commit ]] && return 1
    git cherry-pick "$commit"
}

git-fzf-add () {
    git ls-files --deleted --modified --others --exclude-standard \
        | fzf --ansi --multi --exit-0 \
        | xargs -r git add
}

"git-fzf-$@"
