#!/usr/bin/env python3

import click
import hashlib


@click.command()
@click.argument("algorithm", type=click.Choice(hashlib.algorithms_available))
@click.argument("string")
def hash_str(algorithm, string):
    """Calculate hash of a string."""
    click.echo(hashlib.new(algorithm, string.encode("utf-8")).hexdigest())


if __name__ == "__main__":
    hash_str()
