#!/usr/bin/env bash

export DIR="$HOME/.config/i3/layouts"

if [[ -z $1 ]] ; then
    echo "Usage: $(basename "$0") LAYOUT [WORKSPACE]" >&2
    echo
    echo 'Layouts:'
    for path in "$DIR"/*.{sh,json} ; do
        name="$(basename "$path")"
        echo "  ${name%%.*}"
    done | sort
    exit 2
fi

layout=$1
workspace=$2

if [[ -n $workspace ]] ; then
    i3-msg "workspace $workspace" >/dev/null
fi

if [[ -x $DIR/$layout.sh ]]; then
    "$DIR/$layout.sh" >/dev/null
elif [[ -f $DIR/$layout.json ]] ; then
    i3-msg "append_layout \"$DIR/$layout.json\"" >/dev/null
else
    echo "Layout file '$DIR/$layout.{sh,json}' not exists" >&2
    exit 1
fi
