#!/usr/bin/env python3

import click
import yaml
import json


@click.command()
@click.argument('input_file', type=click.File('r'), default='-')
@click.option('-o', '--output-file', type=click.File('w'), default='-')
@click.option('-w', '--width', type=int, default=80,
              help='Maximal line width')
@click.pass_context
def cli(ctx, input_file, output_file, width):
    """Parse JSON file and print data as YAML."""
    try:
        data = json.load(input_file)
        output_file.write(yaml.dump(data, Dumper=yaml.SafeDumper, width=width))
    except Exception as e:
        click.echo(e, err=True)
        ctx.exit(1)


if __name__ == '__main__':
    # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    cli()
