#!/usr/bin/env python3

from passlib.hash import sha512_crypt

import click


@click.command()
@click.option('-p', '--password', prompt=True, hide_input=True,
              confirmation_prompt=True)
def mkpasswd(password):
    """
    Create password hash for the ansible user module.

    See: https://docs.ansible.com/ansible/latest/modules/user_module.html
    """
    click.echo(sha512_crypt.using(rounds=5000).hash(password))


if __name__ == '__main__':
    mkpasswd()
