#!/usr/bin/env python3

import os
import click
import sh


@click.command()
@click.option('-o', '--output', type=click.Path(file_okay=False), default='')
@click.option('-b', '--bitrate', type=int, default=320)
@click.option('-m', '--ffmpeg-map', default='0', help='See ffmpeg -map option')
@click.argument('files', nargs=-1)
def mp3_from(output, bitrate, ffmpeg_map, files):
    if output and not os.path.isdir(output):
        os.makedirs(output)

    for src in files:
        dst_name = os.path.basename(os.path.splitext(src)[0]) + '.mp3'
        dst = os.path.join(output, dst_name)

        click.secho(f'{src!r} -> {dst!r}', bold=True)
        sh.ffmpeg(
            '-v', 16,
            '-i', src,
            '-map', ffmpeg_map,
            '-codec:a', 'libmp3lame',
            '-b:a', bitrate,
            dst,
            _fg=True,
        )


if __name__ == '__main__':
    # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    mp3_from()
