#!/usr/bin/env bash

bitrate='320k'
output=
map=

if [[ $1 = '--help' ]] ; then
    cat << EOF
Usage: $(basename "$0") [-o DIR] [-b BITRATE] FILE [FILE ...]

Zkonvertuje zadané audio/video soubory na mp3.

Options:
    -o DIR      adresář, do kterého se uloží zkovertované soubory
    -b BITRATE  bitrate výstupní mp3 (default: $bitrate)
    -m MAP      viz ffmpeg map
EOF
    exit
fi

while getopts b:o:m: opt ; do
    case "$opt" in
        b)  bitrate=$OPTARG ;;
        o)  output=$OPTARG ;;
        m)  map=$OPTARG ;;
        *)  echo "Neznámý parametr" >&2 ; exit 1 ;;
    esac
done
((OPTIND--))
shift $OPTIND

if [[ -n $output ]] ; then
    [[ ! -d $output ]] && mkdir -p "$output"
fi

if [[ -z $1 ]] ; then
    echo "Nebyl zadán žádný soubor k převedení"
    exit 127
fi

for src in "${@}" ; do
    mime=$(mimetype --output-format %m "$src")
    case $mime in
        audio/*|video/*)
            dst=$(python -c 'import sys, os; print(os.path.basename(os.path.splitext(sys.argv[1])[0]))' "$src").mp3
            [[ -n $output ]] && dst="$output/$dst"
            ffmpeg -i "$src" ${map:+-map} "$map" -codec:a libmp3lame -b:a "$bitrate" "$dst"
            ;;

        *)
            echo "'$src' není audio ani video soubor (mime: '$mime')" >&2
            ;;
    esac
done
