#!/usr/bin/env bash

[[ $1 == --help ]] && {
    cat <<EOF
Použití: $(basename $0) FILE [FILE...]

Vypise pocet normostran LaTeXovych dokumentu. Makra \\input ani \\include se
nezpracovavaji.
EOF
    exit
}

sum=0
for f ; do
    ns=$(echo "scale=2; `detex -n "$f" | wc -c`/1800;" | bc)
    sum=$(echo "scale = 4; $sum + $ns" | bc)
    LANG=C printf '% 6.2f\t%s\n' $ns "$f"
done
[[ $# -gt 1 ]] && LANG=C printf '% 6.2f\tsum\n' $sum

exit 0
