#!/usr/bin/env bash

#
# Fix Tilda position and size after change of display layout.
#

# Allow pipe output to variable (make work `... | read var`).
shopt -s lastpipe

# Check if primary display is connected, without primary display set this script
# should fail.
xrandr | grep -q 'connected primary' || {
    echo 'Primary display is not connected' >&2
    exit 1
}

config_path () {
    echo -n $HOME/.config/tilda/config_${1:-0}
}

is_tilda_running () {
    test $(pgrep --count --uid $(id -u) tilda) -gt 0
}

kill_tilda () {
    pkill --signal ${1:-SIGTERM} --uid $(id -u) tilda
}

# Kill running tilda to prevent launching multiple times.
kill_tilda

# If tilda is still running try to wait and if still running then force kill.
sleep 0.1 && is_tilda_running && sleep 0.5 && is_tilda_running && kill_tilda SIGKILL

# Keep only one config (config_{1..} is created when tilda is started multiple
# times.
for i in $(seq 1 9) ; do
    rm -f $(config_path $i)
done

# Get size and position of primary display.
xrandr \
    | grep -w primary \
    | sed -re 's/^.* ([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+) .*$/\1 \2 \3 \4/' \
    | read width height x_pos y_pos

# Change tilda config.
sed -re "
s/^max_width=[0-9]+$/max_width=$width/
s/^max_height=[0-9]+$/max_height=$height/
s/^x_pos=[0-9]+$/x_pos=$x_pos/
s/^y_pos=[0-9]+$/y_pos=$y_pos/
" -i $(config_path)

# Start tilda with changed config.
tilda &>/dev/null &
