#!/usr/bin/env bash

SCRIPT=`mktemp /tmp/ts-script.XXXXXX`

if [[ -n $1 ]] ; then
    OLD_SCRIPT=`tsp -i $1 | grep '^Command: /tmp/ts-script.' | cut -d' ' -f2-`
    cat "$OLD_SCRIPT" > "$SCRIPT"
    shift
else
    INT=$(basename $SHELL)
    echo "#!/usr/bin/env $INT" >$SCRIPT
    empty=$(cat $SCRIPT)
fi

$EDITOR $SCRIPT <`tty` >`tty`
chmod +x $SCRIPT

[[ `grep -Pv '^\s*$' $SCRIPT | wc -l` -eq 0 || $(cat $SCRIPT) == $empty ]] \
    && { rm $SCRIPT; exit 1; }

export TS_ENV="$TS_ENV;cat $SCRIPT"
tsp "$@" $SCRIPT
