#!/usr/bin/env python3

import click
import yaml
import json


@click.command()
@click.argument('input_file', type=click.File('r'), default='-')
@click.option('-o', '--output-file', type=click.File('w'), default='-')
@click.option('-p', '--pretty', is_flag=True,
              help='Dump JSON indented')
@click.pass_context
def cli(ctx, input_file, output_file, pretty):
    """Parse YAML file and print data as JSON."""
    try:
        data = yaml.load(input_file.read(), Loader=yaml.SafeLoader)
        json.dump(data, output_file, indent=2 if pretty else None)
        output_file.write('\n')  # json.dump not adds \n at the end
    except Exception as e:
        click.echo(e, err=True)
        ctx.exit(1)


if __name__ == '__main__':
    # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    cli()
