#!/bin/sh

# https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo
alias sudo='sudo -E '

alias e='$EDITOR'
alias f='ranger'
alias g='git'

alias xo='xdg-open'

alias cat='bat -p'

alias ls='ls -v --color=auto --hyperlink=auto -CF'
alias l='ls'
alias ll='l -hl --time-style="+%Y-%m-%d %H:%M"'
alias la='l -A'
alias lla='ll -A'

# COW copy if available
alias cp='cp --reflink=auto'

alias rcp='rsync -hhh --info=progress2'

# Human readable sizes
alias du='grc du -khc'
alias df='grc df -kTh'
alias free='grc free -th'

alias rg='rg -S'
alias rgl='rg -l'

# force 256 colors
alias tmux='tmux -2'

# Copy & Paste clipboard
alias ci='xsel -ib'
alias co='xsel -ob'

alias bc='bc -ql'

# Enable colors and aliasses expansion.
alias watch='watch --color '
alias grcwatch='watch --color grc --colour=on '

alias pa='pueue add -- '

alias py='python3'
alias pydoc='pydoc3'

# Extra aliasses in Kitty terminal
if [ "$TERM" = xterm-kitty ] && command -v kitty > /dev/null 2>&1 ; then
    alias :new='kitty --detach '

    alias kitten='kitty +kitten'
    # SSH kitten is wrapper around ssh command that fixes terminfo and adds some
    # extra features.
    alias ssh='kitty +kitten ssh'
    # cat image.
    alias icat='kitty +kitten icat'
fi
