#!/bin/zsh
# This hook is run when the list of virtualenvs is printed so each name can include details.
# argument: environment name

virtualenv_name=$1
virtualenv_path=$WORKON_HOME/$virtualenv_name

get_version () { "$1" --version | cut -d' ' -f2 }

echo 'Versions: '
echo "  python: $("$virtualenv_path/bin/python" --version | cut -d' ' -f2)"
echo "  pip: $("$virtualenv_path/bin/pip" --version | cut -d' ' -f2)"

if [[ -f $virtualenv_path/.project ]] ; then
    project=$(cat $virtualenv_path/.project)
    echo "Project: $project"
fi
