#!/bin/zsh
# This hook is run when the list of virtualenvs is printed so each name can include details.
# argument: environment name

virtualenv_name=$1
virtualenv_path=$WORKON_HOME/$virtualenv_name

echo "Python: $(readlink "$virtualenv_path/bin/python")"

if [[ -f $virtualenv_path/.project ]] ; then
    echo -n 'Project: '
    cat $virtualenv_path/.project
fi
