#!/bin/zsh
# This hook is run when the list of virtualenvs is printed so each name can include details.
# argument: environment name

virtualenv_name=$1

if [[ -f $WORKON_HOME/$virtualenv_name/.project ]] ; then
    echo -n 'Project: '
    cat $WORKON_HOME/$virtualenv_name/.project
fi
