#!/bin/zsh
# This hook is sourced after every virtualenv is activated.

# Update cached $PATH entries
rehash

# Change default behavior of `cd` (without parameters). Lets cd to know about
# virtualenv and istead of going to ~ go to virtualenv root.
cd () {
    if (( $# == 0 ))
    then
        cdproject
    else
        builtin cd "$@"
    fi
}

pycov () {
    tests_dir=${1:-tests}
    coverage run -m unittest discover "$tests_dir" 2>/dev/null
    if [[ $? -ne 0 ]] ; then
        echo 'Tests failed' >&2
        return 1
    fi
    coverage report -m --omit="$tests_dir/*"
}
