#!/bin/zsh
# This hook is sourced after every virtualenv is activated.

# Update cached $PATH entries
rehash

# Change default behavior of `cd` (without parameters). Lets cd to know about
# virtualenv and istead of going to ~ go to virtualenv root.
cd () {
    if (( $# == 0 ))
    then
        cdproject
    else
        builtin cd "$@"
    fi
}
