#!/bin/sh

# If GNOME is installed
if which gnome-session >/dev/null 2>&1 ; then

    # Start GNOME session (starts settings-daemon, autostart applications, ...)
    gnome-session &

# If MATE is installed
elif which gnome-session >/dev/null 2>&1 ; then

    # Settings Demon
    mate-settings-daemon &

    # Applets
    nm-applet &
    mate-volume-control-applet &
    mate-power-manager &

# Otherwise is nothing installed ?!
else
    exit 1
fi

# Keyring
gnome-keyring-daemon -dl &

# X compositor
compton -b &

# Dropdown terminal
tilda &

# Swap CapsLock and Escape
setxkbmap -option caps:escape &

# Wallpaper
test -x ~/.fehbg && ~/.fehbg &

# Applications
test -x ~/.autostart && ~/.autostart &
