#!/usr/bin/env bash

export WLAN_INTERFACE=$(ip -br link show | awk '/^wl/ { print $1 ; nextfile }')

# Terminate already running bar instances.
pkill -U $UID polybar

# Start polybar on all monitors.
polybar --list-monitors | while read line ; do
    export MONITOR=$(echo $line | cut -d":" -f1)
    export BAR=$(echo $line | grep -q primary && echo primary || echo secondary)
    systemd-cat -t polybar/$MONITOR polybar --reload $BAR &
done
