#!/usr/bin/env zsh

umask g-w,o-w
cd "$HOME"

echo '>>> Update Git submodules'
yadm submodule update --recursive --init

echo '>>> Change Git push URL'
yadm remote set-url --push origin 'git@gitlab.com:fpob/dotfiles.git'

echo '>>> Build YouCompleteMe'
.vim/pack/dev/start/youcompleteme/install.py

echo '>>> Generate Vim helptags'
find .vim/pack -maxdepth 4 -name doc -type d -exec vim -T dumb -e -c 'helptags {}' -c q \;
