#!/usr/bin/env zsh

umask g-w,o-w
cd "$HOME"

[[ ! -n $ZSH ]] && ZSH=$HOME/.oh-my-zsh

echo '>>> Initialize Oh My Zsh'
[[ ! -f $ZSH/oh-my-zsh.sh ]] && {
    cd "$ZSH"
    git init
    git remote add origin 'https://github.com/robbyrussell/oh-my-zsh.git'
    cd "$HOME"
}

echo '>>> Update Oh My Zsh'
git -C "$ZSH" pull origin master

echo '>>> Update Git submodules'
yadm submodule update --recursive --init

echo '>>> Change Git push URL'
yadm remote set-url --push origin 'git@gitlab.com:fpob/dotfiles.git'

echo '>>> Build YouCompleteMe'
.vim/pack/dev/start/youcompleteme/install.py

echo '>>> Generate Vim helptags'
find .vim/pack -maxdepth 4 -name doc -type d -exec vim -T dumb -e -c 'helptags {}' -c q \;
