#!/usr/bin/env zsh

umask g-w,o-w
cd "$HOME"

# Install Oh My Zsh
[[ ! -n $ZSH ]] && ZSH=$HOME/.oh-my-zsh
[[ ! -d $ZSH ]] && git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git "$ZSH"

# Init submodules
yadm submodule update --recursive --init

# Init vim
make -C .vim init

ln -s $HOME/.vim $HOME/.config/nvim
